DROP VIEW IF EXISTS Ugedage;
DROP VIEW IF EXISTS ContactInfo;
DROP VIEW IF EXISTS Scala;
DROP VIEW IF EXISTS ButikkeriRegion;

DROP TABLE IF EXISTS Volunteer;
DROP TABLE IF EXISTS Coordinator;
DROP TABLE IF EXISTS hasProgram;
DROP TABLE IF EXISTS Store;
